### ISSUE TITLE
lepiterPage sent to QuTranscript returns a KeyNotFound error

### ISSUE THREAD

**Issue by RalfBarkow** [seandenigris/Quote-Me#12]
KeyNotFound: key QuLeTranscriptPageType not found in IdentityDictionary

I'm following your Dynabook Demo: Transcripts at [16:32](https://youtu.be/EDpY-WqPKJY?t=992). As I don't have a Lepiter page yet I tried to send `lepiterPage` to my QuTranscript.

**Comment by RalfBarkow** [comment]
Nonetheless, I have just gotten this far
<img width="1552" alt="Bildschirmfoto 2022-02-19 um 13 58 44" src="https://user-images.githubusercontent.com/1205477/154801827-832df042-3e57-4c26-a7cf-7e32a4715191.png">
.

**Comment by seandenigris** [comment]
The problem was that Lepiter does not pick up new page types if they are loaded after the primary DB. In my load script, I always load the DB *after* Dynabook so I never ran into the issue. Thanks for the report!
