### ISSUE TITLE
Applescripts Targeting Safari Fail if Developer Setting Not Enabled

### ISSUE THREAD

**Issue by RalfBarkow** [seandenigris/Quote-Me#13]
Instance of ApplescriptReference did not understand #ifFalse: 

<img width="1438" alt="Bildschirmfoto 2022-02-19 um 17 36 12" src="https://user-images.githubusercontent.com/1205477/154809831-392b5394-8a80-4384-b2d5-a5f1c85d83d2.png">

Click, e.g., `Play`

**Comment by seandenigris** [comment]
I have an idea what the problem is. I’d like to see a few more steps down in the call chain and the debugger.

**Comment by RalfBarkow** [comment]
<img width="1312" alt="Bildschirmfoto 2022-02-19 um 17 42 15" src="https://user-images.githubusercontent.com/1205477/154810105-d2b98faf-39b5-4ff2-b9d7-764459370bb9.png">

**Comment by seandenigris** [comment]
Try enabling this setting in Safari:
<img width="757" alt="Screen Shot 2022-02-19 at 11 42 25 AM" src="https://user-images.githubusercontent.com/184176/154810149-170f2126-d479-4579-9a39-c561a49115b2.png">

**Comment by RalfBarkow** [comment]
`Allow JavaScript from Apple Events` fixed this issue

**Comment by seandenigris** [comment]
I'll see if I can put in a check; maybe give a better error message

**Comment by seandenigris** [comment]
Recorded the AppleScript issue here: https://github.com/seandenigris/Computer-World/issues/13

**Comment by seandenigris** [comment]
Found a good hook to check for this particular case: https://github.com/seandenigris/Living-Library/commit/02a80c00f91b0878cef7e306a1e968ada1f89712
