### ISSUE TITLE
Transcript lines lose timestamp

### ISSUE THREAD

**Issue by RalfBarkow** [seandenigris/Quote-Me#15]
<img width="1392" alt="Bildschirmfoto 2022-02-25 um 14 31 56" src="https://user-images.githubusercontent.com/1205477/155723951-3c10537d-d95d-4876-a287-743a30ccf7fd.png">

**Comment by RalfBarkow** [comment]
Same page as correctly displayed on my computer R:
<img width="1049" alt="Bildschirmfoto 2022-02-25 um 14 37 20" src="https://user-images.githubusercontent.com/1205477/155724784-695ee9a8-fd14-484a-ab8a-49af6305505e.png">

**Comment by seandenigris** [comment]
If you check Work -> Transcript -> Line in each image, what is the state (e.g. UID, timestamp)?

**Comment by seandenigris** [comment]
I haven’t seen this and there is no update so I will close. We can reopen if needed
